project:
  type: website

website:
  search: false
  title: "Joe Blogs"
  navbar:
    left:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com

format:
  html:
    ## Use the 'lux' theme instead of 'cosmo'
    theme: lux
    css: styles.css
    toc: true